### ISSUE TITLE
Граббер для сайта на заказ

### ISSUE THREAD

**Issue by 6ashmak** [lirix360/ReadmangaGrabber#13]
А такой же граббер но для сайта на заказ можете написать?
Нужен такой же граббер для CMS DLE.

**Comment by ParTy-Play-go** [comment]
> А такой же граббер но для сайта на заказ можете написать?
> Нужен такой же граббер для CMS DLE.

Извините, но как?) Граббер собирает инфу с сайтов, а не взламывает что-либо)

**Comment by ParTy-Play-go** [comment]
> А такой же граббер но для сайта на заказ можете написать?
> Нужен такой же граббер для CMS DLE.

И просьба, не пишите заказы в issues.
