### ISSUE TITLE
elem is not defined

### ISSUE THREAD

**Issue by NiackZ** [lirix360/ReadmangaGrabber#17]
Ошибка при любом скачивании

![2021-09-07_00-49-35](https://user-images.githubusercontent.com/14057913/132257008-e1e51869-06eb-4997-a4c9-7ddb42531db8.png)
![2021-09-07_00-49-21](https://user-images.githubusercontent.com/14057913/132257012-2a4d09d8-1240-40b6-ab88-ca295e838bc9.png)

**Comment by lirix360** [comment]
Исправлено в beta 3.
