### ISSUE TITLE
Ошибка при запуске / сохранение настроек

### ISSUE THREAD

**Issue by Harpagon** [lirix360/ReadmangaGrabber#23]
Добрый день, только что скомпиллировал приложение, но при запуске в логе только ошибка, что не может открыть конфиг, которого нет в папке с кодом. Помогло создание пустого JSON-файла `grabber_config.json` с текстом `{}`.
Но после запуска в настройках поменял параметры, но в файл конфигурации они не записались.

**Comment by lirix360** [comment]
> Добрый день, только что скомпиллировал приложение, но при запуске в логе только ошибка, что не может открыть конфиг, которого нет в папке с кодом. Помогло создание пустого JSON-файла `grabber_config.json` с текстом `{}`.
> Но после запуска в настройках поменял параметры, но в файл конфигурации они не записались.

В релизах в архивах есть конфиг.
