### ISSUE TITLE
Проблемы с MangaLib

### ISSUE THREAD

**Issue by ParTy-Play-go** [lirix360/ReadmangaGrabber#31]
Ошибка вида FATAL: Не удается получить данные сайта
И это не ошибка не доступности MangaLib.
Я использую свой патч, с некоторыми удобствами, но видимо из-за него возникают проблемы.

**Comment by lirix360** [comment]
MangaLib не поддерживается начиная с beta 3. Возобновления поддержки пока не планируется.
