### ISSUE TITLE
Downloading whole volume // Скачивание тома полностью

### ISSUE THREAD

**Issue by Hanqnero** [lirix360/ReadmangaGrabber#7]
Is it possible to download whole volume, without typing all chapter numbers?
Можно ли скачать том манги полностью, не перечисляя всего его главы вручную?

**Comment by lirix360** [comment]
> Is it possible to download whole volume, without typing all chapter numbers?
> Можно ли скачать том манги полностью, не перечисляя всего его главы вручную?

На данный момент невозможно.
Добавлю в доработки.
