### ISSUE TITLE
Add mirror support https://23.mintmanga.one/

### ISSUE THREAD

**Issue by My12123** [lirix360/ReadmangaGrabber#91]
- [x] Add mirror support https://23.mintmanga.one/
- [x] #92

**Comment by lirix360** [comment]
Mirror added

**Comment by My12123** [comment]
Thank you, will there be a new version for Windows?

**Comment by lirix360** [comment]
> Thank you, will there be a new version for Windows? How did you implement automatic mirror updates?

The up-to-date list of mirrors is downloaded by the latest version of the program at startup. There is no need to update the program.

**Comment by My12123** [comment]
What to do if cookies are empty?
![2023-11-05_16-42-42](https://github.com/lirix360/ReadmangaGrabber/assets/49092250/d6aa2689-0453-4fa6-aca7-91d2532ec41c)

**Comment by My12123** [comment]
What to do if cookies are empty?
![2023-11-05_16-42-42](https://github.com/lirix360/ReadmangaGrabber/assets/49092250/b2bb669b-dd0e-4d17-ae2b-2edc515a6ed1)

**Comment by lirix360** [comment]
> What to do if cookies are empty? ![2023-11-05_16-42-42](https://user-images.githubusercontent.com/49092250/280530973-b2bb669b-dd0e-4d17-ae2b-2edc515a6ed1.png)

I don't know. I have everything in place. Try deleting cookies for the site and logging in again, or a different browser.
